### ISSUE TITLE
Multiple Radeon Vii's

### ISSUE THREAD

**Issue by roblem** [lwilletts/radeonvii#1]
Does this assume only 1 radeon vii?  I have 2 and typically (but not always) 1 is for tensorflow and runs at 100% for days while the other is for desktop gui.  Would the systemd service handle independent fan setting for each one?

**Comment by lwilletts** [comment]
Yes. The script would have to modified so that you could specify each card separately, in particular here:

```
    # find correct card
    i=0
    while :; do
        radeonPCI="/sys/class/drm/card$i/device"
        uevent="$radeonPCI/uevent"

        while :; do
            test -e "$uevent" && break
        done

        driver="$(awk -F '=' '/DRIVER/ {print $2}' "$uevent")"
        test "$driver" = "amdgpu" && break

        i="$((i + 1))"
        test "$i" -eq 4 && i=0
    done
```

As the card is directly accessible by finding it in /sys/class/drm/ you would have to find some way of making sure the card0 or card1 in your system corresponds to the card you want to adjust. IIRC card0, card1 etc can change between reboot hence this block of code exists the way it does as I have mulitple gpu's in my system but only my radeon VII is obviously using the amdgpu driver.

Perhaps this could be checked for in your use case by checking the unique_id value in /sys/class/drm/card$i/device/unique_id

**Comment by roblem** [comment]
Thanks. I'll experiment and report back (it may be awhile). Since I only have radeon vii's, I might just hardwire the hardware check.

**Comment by roblem** [comment]
Based on your work, I have modified the radeon script and systemd service files to suit my needs: 1) I don't want to mess with any voltages or memory timings, and 2) I just want a more aggressive fan curve to keep the junction temp below 80.  Also, I use the rocm-smi script to do all the setting for me.  Here are the files in case anybody wants to see them .  The bash script (`radeon_fan_curve.sh`) that sets the fan curve conditionally on temperatures is:
```bash
#!/bin/bash
cardidx=$1 
radeonPCI="/sys/class/drm/card$cardidx/device"

while :; do

        TEMP="$(($(cat "$radeonPCI/hwmon/hwmon$cardidx/temp2_input") / 1000))"

        case $TEMP in
            [0-5][0-9])  /opt/rocm/bin/rocm-smi "-d$cardidx" --resetfans > /dev/null ;;
            6[0-4])      /opt/rocm/bin/rocm-smi "-d$cardidx" --setfan 35% > /dev/null ;;
	    6[5-9])	 /opt/rocm/bin/rocm-smi "-d$cardidx" --setfan 38% > /dev/null ;;
	    7[0-4])	 /opt/rocm/bin/rocm-smi "-d$cardidx" --setfan 42% > /dev/null ;;
	    7[5-9])	 /opt/rocm/bin/rocm-smi "-d$cardidx" --setfan 47% > /dev/null ;;
	    8[0-9])	 /opt/rocm/bin/rocm-smi "-d$cardidx" --setfan 55% > /dev/null ;;
	    9[0-9])	 /opt/rocm/bin/rocm-smi "-d$cardidx" --setfan 85% > /dev/null ;;
	    1[0-9][0-9]) /opt/rocm/bin/rocm-smi "-d$cardidx" --setfan 100% > /dev/null ;;
        esac

        sleep 3
done
```
I have a systemd service file for each GPU that calls the above script and passes either 0 [GPU 0] or 1 [GPU 1], which are the only two GPUs I have in my system and both are radeon vii's:
```bash
[Unit]
Description=Radeon VII (GPU 1)

[Service]
Type=simple
ExecStart=/home/username/Dropbox/linux/scripts/radeon_fan_curve.sh 1 

[Install]
WantedBy=multi-user.target

```
One thing I would note is that the temperature file location has GPU id in it twice: `TEMP="$(($(cat "$radeonPCI/hwmon/hwmon$cardidx/temp2_input") / 1000))"` (since `radeonPCI` contains the cards index number), whereas, in your script you hardcode the second of these as `hwmon2`: 

https://github.com/lwilletts/radeonvii/blob/635fe982f41ea9f5a0ebdad5e74bb4b1339cc484/radeon#L79
